import test from 'node:test';
import assert from 'node:assert/strict';
import {readNumber,normalizeSearch,readFilters,csvCell,electionCsv} from '../lib/election-core.mjs';
test('missing numbers remain unavailable',()=>{for(const v of [null,undefined,'','bad'])assert.equal(readNumber(v),null);assert.equal(readNumber('0'),0);assert.equal(readNumber('23,5'),23.5);});
test('search ignores accents',()=>assert.equal(normalizeSearch(' São João '),'sao joao'));
test('filters validate geography and office',()=>{assert.equal(readFilters('?uf=xx&office=6',['sp']).office,'1');assert.equal(readFilters('?uf=df&office=8',['df']).office,'7');assert.equal(readFilters('?uf=sp&office=6&turn=2',['sp']).office,'1');});
test('CSV exports all candidates and labels stale data',()=>{const candidates=Array.from({length:1045},(_,id)=>({id,name:'João',votes:0}));const csv=electionCsv({candidates,stale:true},{uf:'sp',office:'6'});assert.equal(csv.split('\r\n').length,1046);assert.ok(csv.includes('"sim"'));assert.equal(csvCell('=formula'),'"\'=formula"');assert.equal(csvCell('a"b'),'"a""b"');});
test('elected candidates precede higher-vote non-elected candidates',async()=>{
 const {compareCandidates,isElected}=await import('../lib/election-core.mjs');
 for(const s of ['Eleito','ELEITO POR QP','Eleito por média','Eleita'])assert.equal(isElected(s),true);
 for(const s of ['Não eleito','Suplente','2º turno','',null,'Eleito pendente'])assert.equal(isElected(s),false);
 const rows=[{name:'Líder',votes:1000,situation:'Não eleito'},{name:'B',votes:50,situation:'Eleito por média'},{name:'A',votes:100,situation:'Eleito por QP'},{name:'Suplente',votes:300,situation:'Suplente'}];
 assert.deepEqual(rows.sort(compareCandidates).map(c=>c.name),['A','B','Líder','Suplente']);
 rows[0].situation='Não eleito';rows[2].situation='Eleito';
 assert.equal(rows.sort(compareCandidates)[0].name,'Líder');
 assert.deepEqual([{name:'Z',votes:null},{name:'B',votes:0},{name:'A',votes:0}].sort(compareCandidates).map(c=>c.name),['A','B','Z']);
});
test('final badge requires explicit finalization, not partial election status',async()=>{const {electionBadge}=await import('../lib/election-core.mjs');for(const office of ['5','6','7']){assert.equal(electionBadge(office,'Eleito por QP',false),'Na zona de eleição · provisório');assert.equal(electionBadge(office,'Eleito',undefined),'Na zona de eleição · provisório');assert.equal(electionBadge(office,'Eleito',true),'✓ Eleito · TSE');assert.equal(electionBadge(office,'Suplente',true),null);}assert.equal(electionBadge('1','Eleito',false),null);});

test('presidential and governor badges require final totals and official status',async()=>{const {electionBadge,isSecondRound}=await import('../lib/election-core.mjs');for(const office of ['1','3']){for(const s of ['Eleito','2º turno'])for(const finished of [false,undefined])assert.equal(electionBadge(office,s,finished),null);assert.equal(electionBadge(office,'Eleito',true),'✓ Eleito · TSE');assert.equal(electionBadge(office,'2º turno',true),'Vai para o 2º turno · TSE');for(const s of ['Não eleito','',null,'Suplente'])assert.equal(electionBadge(office,s,true),null);}for(const s of ['2º turno','2° Turno','2o turno','2 turno'])assert.equal(isSecondRound(s),true);assert.equal(isSecondRound('Não vai ao 2º turno'),false);assert.equal(electionBadge('5','2º turno',true),null);});
test('mathematical bounds are strict and reject missing, stale, local or judicial data',async()=>{const {mathematicalWinners,electionBadge}=await import('../lib/election-core.mjs');const data={and:'p',t:'1',e:{te:100,esa:90},v:{vv:90,van:0,vansj:0},carg:[{cd:'1',nv:'1',agr:[{par:[{cand:[{sqcand:'a',vap:60,dvt:'Válido'},{sqcand:'b',vap:30,dvt:'Válido'}]}]}]}]};assert.deepEqual(mathematicalWinners(data,'1','br','all'),['a']);assert.equal(electionBadge('1','',false,true),'Matematicamente eleito · cálculo do painel');for(const args of [['1','sp','all'],['1','br','12345'],['6','sp','all']])assert.deepEqual(mathematicalWinners(data,...args),[]);assert.deepEqual(mathematicalWinners(data,'1','br','all',true),[]);for(const change of [{e:{te:100}},{v:{vv:90,van:0,vansj:1}},{and:'f'}])assert.deepEqual(mathematicalWinners({...data,...change},'1','br','all'),[]);data.carg[0].agr[0].par[0].cand[0].vap=50;data.carg[0].agr[0].par[0].cand[1].vap=40;assert.deepEqual(mathematicalWinners(data,'1','br','all'),[]);});
test('senate uses official seat count and conservative two-vote bound',async()=>{const {mathematicalWinners}=await import('../lib/election-core.mjs');const d={and:'p',t:'1',e:{te:100,esa:95},v:{vv:170,van:0,vansj:0},carg:[{cd:'5',nv:2,agr:[{par:[{cand:[{sqcand:'a',vap:80,dvt:'Válido'},{sqcand:'b',vap:70,dvt:'Válido'},{sqcand:'c',vap:20,dvt:'Válido'}]}]}]}]};assert.deepEqual(mathematicalWinners(d,'5','sp','all'),['a','b']);d.carg[0].nv=undefined;assert.deepEqual(mathematicalWinners(d,'5','sp','all'),[]);});

test('judicial votes are bounded against valid winners rather than blocking every highlight',async()=>{const {mathematicalWinners}=await import('../lib/election-core.mjs');const d={and:'p',t:'1',e:{te:100,esa:90},v:{vv:85,van:0,vansj:5},carg:[{cd:'3',nv:1,agr:[{par:[{cand:[{sqcand:'a',vap:60,dvt:'Válido'},{sqcand:'b',vap:25,dvt:'Válido'},{sqcand:'j',vap:5,dvt:'Anulado sub judice'}]}]}]}]};assert.deepEqual(mathematicalWinners(d,'3','pi','all'),['a']);d.carg[0].agr[0].par[0].cand[0].vap=50;d.carg[0].agr[0].par[0].cand[1].vap=35;assert.deepEqual(mathematicalWinners(d,'3','pi','all'),[]);d.v.vansj=6;assert.deepEqual(mathematicalWinners(d,'3','pi','all'),[]);});