"use client";
import {useEffect,useState} from 'react';
import {Radio,RefreshCw,Clock,Search,ExternalLink} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Progress} from '@/components/ui/progress';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {states,tiles} from '@/lib/geography';
const num=(v:unknown)=>v==null?'—':Number(v).toLocaleString('pt-BR');
const pct=(v:unknown)=>v==null?'—':Number(v).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})+'%';
type Candidate={name:string;number:string;party:string;votes:number;percent:number;situation:string};
type Result={status:string;message?:string;updated?:string;progress?:number;counted?:number;total?:number;valid?:number;blank?:number;nullVotes?:number;candidates?:Candidate[];source?:string;stale?:boolean;states?:{uf:string;progress:number;status:string}[]};
export default function Home(){
 const [uf,U]=useState('br'),[office,O]=useState('1'),[town,M]=useState('all'),[turn,T]=useState('1'),[query,Q]=useState(''),[result,R]=useState<Result|null>(null),[summary,S]=useState<Result|null>(null),[towns,C]=useState<{cd:string;nm:string}[]>([]),[townError,E]=useState(false),[loading,L]=useState(true),[tick,X]=useState(0);
 const cargo=office==='7'&&uf==='df'?'8':office;
 const chooseUf=(v:string)=>{U(v);M('all');if(v==='br')O('1');};
 useEffect(()=>{let alive=true;const ctl=new AbortController();R(null);L(true);const load=async()=>{if(document.hidden)return;try{const r=await fetch(`/api/tse?kind=result&uf=${uf}&office=${cargo}&town=${town}&turn=${turn}`,{signal:ctl.signal});const d=await r.json();if(alive)R(d as Result);}catch{if(alive&&!ctl.signal.aborted)R({status:'error',message:'Atualização indisponível. Tentaremos novamente automaticamente.'});}finally{if(alive)L(false);}};load();const id=setInterval(load,30000);return()=>{alive=false;ctl.abort();clearInterval(id);};},[uf,cargo,town,turn,tick]);
 useEffect(()=>{let alive=true;const load=async()=>{if(document.hidden)return;try{const r=await fetch(`/api/tse?kind=summary&turn=${turn}`);if(alive)S(await r.json() as Result);}catch{if(alive)S({status:'error'});}};load();const id=setInterval(load,30000);return()=>{alive=false;clearInterval(id);};},[turn,tick]);
 useEffect(()=>{let alive=true;C([]);E(false);if(uf!=='br')fetch(`/api/tse?kind=towns&uf=${uf}&turn=${turn}`).then(r=>r.json()).then(d=>{if(alive){C((d as {towns?:{cd:string;nm:string}[]}).towns??[]);E((d as {status:string}).status!=='ok');}}).catch(()=>{if(alive)E(true);});return()=>{alive=false;};},[uf,turn]);
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>}}).modelContext;if(!ctx)return;const ctl=new AbortController();Promise.resolve(ctx.registerTool({name:'read_election_results',description:'Read the official TSE results currently visible in this panel.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({uf,office:cargo,town,turn,result})},{signal:ctl.signal})).catch(()=>{});return()=>ctl.abort();},[uf,cargo,town,turn,result]);
 const title=office==='1'?'Presidente da República':office==='3'?'Governador':office==='5'?'Senador':office==='6'?'Deputado federal':uf==='df'?'Deputado distrital':'Deputado estadual';
 const place=town!=='all'?towns.find(t=>t.cd===town)?.nm:uf==='br'?'Brasil':states.find(s=>s[0]===uf)?.[1];
 const list=(result?.candidates??[]).filter(c=>`${c.name} ${c.number} ${c.party}`.toLowerCase().includes(query.toLowerCase()));
 const picker=(value:string,set:(v:string)=>void,items:[string,string][],label:string,disabled=false)=><Select value={value} onValueChange={set} disabled={disabled}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(([v,n])=><SelectItem key={v} value={v}>{n}</SelectItem>)}</SelectContent></Select>;
 return <><header><div className="brand"><img src="/logo.png" alt="Na Boca do Povo"/><div><span className="eyebrow">COBERTURA ESPECIAL</span><strong>ELEIÇÕES <em>2026</em></strong></div></div><a className="source" href="https://resultados.tse.jus.br/" target="_blank" rel="noreferrer">Fonte oficial: TSE <ExternalLink size={16}/></a></header><main><div className="headline"><div><span className="eyebrow blue">O BRASIL NAS URNAS</span><h1>Acompanhe cada voto.</h1><p>Resultados oficiais, de todo o país, no Na Boca do Povo.</p></div><div className="edition"><Radio/><div><strong>{turn==='1'?'04':'25'} de outubro</strong><span>{turn}º turno · Eleições 2026</span></div></div></div>
 <section className="filters" aria-label="Filtros"><label>Turno{picker(turn,v=>{T(v);M('all');if(v==='2')O('1');},[['1','1º turno'],['2','2º turno']],'Turno')}</label><label>Estado{picker(uf,chooseUf,[['br','Brasil inteiro'],...states],'Estado')}</label><label>Cargo{picker(office,O,uf==='br'?[['1','Presidente']]:turn==='2'?[['1','Presidente'],['3','Governador']]:[['1','Presidente'],['3','Governador'],['5','Senador'],['6','Deputado federal'],['7',uf==='df'?'Deputado distrital':'Deputado estadual']],'Cargo')}</label><label>Município{picker(town,M,[['all',uf==='br'?'Selecione um estado':'Todos os municípios'],...towns.map(t=>[t.cd,t.nm] as [string,string])],'Município',uf==='br'||!towns.length)}</label><button className="refresh" aria-label="Atualizar resultados" disabled={loading} onClick={()=>X(x=>x+1)}><RefreshCw size={20} className={loading?'spin':''}/></button></section>
 {townError&&<p className="notice">A lista de municípios ainda não pôde ser consultada no TSE.</p>}<div className="statusline" aria-live="polite"><span><Clock size={16}/>{loading?'Consultando o TSE…':result?.stale?'Atualização indisponível · exibindo último resultado recebido':result?.message??'Aguardando a divulgação oficial'}</span><span>Consulta automática a cada 30 segundos</span></div>
 <div className="dashboard"><section className="panel results"><div className="panel-head"><div><span className="eyebrow blue">{place} · {turn}º TURNO</span><h2>{title}</h2></div><span className="badge">{result?.status==='ok'?'Oficial':'Aguardando'}</span></div><div className="counting"><div><span>Seções totalizadas</span><strong>{pct(result?.progress)}</strong></div><Progress value={result?.progress??0}/><p>{result?.total!=null?`${num(result.counted)} de ${num(result.total)} seções`:'O percentual aparecerá quando o TSE disponibilizar a totalização.'}</p></div><div className="search"><Search size={18}/><input aria-label="Buscar candidato, número ou partido" placeholder="Buscar candidato, número ou partido" value={query} onChange={e=>Q(e.target.value)}/></div>
 {list.length?<Table><TableHeader><TableRow><TableHead>Candidato / partido</TableHead><TableHead className="numeric">Votos</TableHead><TableHead className="numeric">%</TableHead></TableRow></TableHeader><TableBody>{list.map((c,i)=><TableRow key={c.number}><TableCell><div className="candidate"><span className="number">{c.number}</span><div><strong>{c.name}</strong><small>{c.party}{c.situation?' · '+c.situation:''}</small><div className="vote-bar"><span style={{width:`${Math.min(c.percent,100)}%`,background:i===0?'#0766ad':'#718da4'}}/></div></div></div></TableCell><TableCell className="numeric">{num(c.votes)}</TableCell><TableCell className="numeric"><strong>{pct(c.percent)}</strong></TableCell></TableRow>)}</TableBody></Table>:<div className="empty"><Radio size={34}/><h3>{query?'Nenhum candidato encontrado':loading?'Consultando os resultados':result?.status==='ok'?'Apuração não iniciada':'Aguardando a divulgação'}</h3><p>{query?'Tente outro nome, número ou partido.':'Os candidatos e votos aparecerão aqui conforme a publicação dos arquivos oficiais do TSE.'}</p></div>}
 <div className="stats">{[['Votos válidos',result?.valid],['Brancos',result?.blank],['Nulos',result?.nullVotes]].map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{num(value)}</strong></div>)}</div><div className="timestamp">Última totalização: {result?.updated??'ainda não disponível'}{result?.source&&<> · <a href={result.source} target="_blank" rel="noreferrer">Arquivo do TSE</a></>}</div></section>
 <aside className="panel"><div className="panel-head"><div><span className="eyebrow blue">PANORAMA NACIONAL</span><h2>Apuração pelo Brasil</h2></div></div><p className="map-caption">Selecione uma UF para ver seus resultados.</p><div className="tile-map" aria-label="Mapa esquemático dos estados">{tiles.map(([s,x,y])=>{const d=summary?.states?.find(v=>v.uf===s);return <button key={s} style={{gridColumn:x,gridRow:y}} className={uf===s?'selected':''} onClick={()=>chooseUf(s)} aria-label={`${states.find(v=>v[0]===s)?.[1]}: ${pct(d?.progress)}`}>{s.toUpperCase()}<small>{d ? Math.round(d.progress)+'%' : '—'}</small></button>;})}</div><div className="legend"><span><i/>Sem dados / em apuração</span><span><i className="yellow"/>UF selecionada</span></div><p className="fine">Mapa esquemático · Totalização da eleição estadual</p><div className="state-list">{states.map(([s,n])=><button key={s} className={s===uf?'active':''} onClick={()=>chooseUf(s)}><span>{n}</span><strong>{pct(summary?.states?.find(v=>v.uf===s)?.progress)}</strong></button>)}</div>{summary?.status==='error'&&<p className="notice">O panorama nacional não pôde ser atualizado.</p>}</aside></div>
 <footer><strong>NA BOCA DO POVO <span>· ELEIÇÕES 2026</span></strong><p>Dados: Tribunal Superior Eleitoral. Painel independente do programa Na Boca do Povo.</p><p>Resultados parciais podem mudar. A situação dos candidatos segue a informação do TSE.</p><a href="https://resultados.tse.jus.br/" target="_blank" rel="noreferrer">Conferir no TSE <ExternalLink size={14}/></a></footer></main></>;
}


