import type {Indicators} from '@/lib/election-indicators';
const num=(v:number|null|undefined)=>v==null?'—':v.toLocaleString('pt-BR');
const pct=(v:number|null|undefined)=>v==null?'—':v.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})+'%';
export function ElectionNumbers({data,place,office}:{data?:Indicators;place:string;office:string}){
 const rate=(n:number|null|undefined)=>n!=null&&data?.votes!=null&&data.votes>0?pct(n/data.votes*100):'—';
 const participation=(n:number|null|undefined)=>data?.installed!=null&&data.installed>0?pct(n):'—';
 const cards=[['Eleitores aptos',data?.eligible,'Total do eleitorado'],['Eleitores em seções totalizadas',data?.covered,`${pct(data?.coveredPercent)} do eleitorado`],['Eleitores em seções pendentes',data?.pending,'Aguardando totalização'],['Comparecimento',data?.turnout,`${participation(data?.turnoutPercent)} · taxa do TSE`],['Abstenção',data?.abstention,`${participation(data?.abstentionPercent)} · taxa do TSE`],['Total de votos computados',data?.votes,'Para o cargo selecionado']] as const;
 const rows=[['Votos válidos',data?.valid],['Brancos',data?.blank],['Nulos',data?.nullVotes],['Anulados',data?.annulled],['Anulados sub judice',data?.subJudice]] as const;
 return <section className="election-numbers" aria-label={`Indicadores eleitorais de ${place}`}><div className="numbers-heading"><h3>Eleitorado e votação</h3><span>{place}</span></div><dl className="electorate-grid">{cards.map(([label,value,note],i)=><div key={label} className={i===0?'metric featured':'metric'}><dt>{label}</dt><dd>{num(value)}</dd><small>{note}</small></div>)}</dl><p className="numbers-note">Comparecimento e abstenção refletem as seções já totalizadas. As taxas do TSE usam o eleitorado das seções instaladas: <strong>{num(data?.installed)}</strong> eleitores.</p><div className="voting-summary"><div className="voting-heading"><strong>Composição dos votos</strong><span>% do total computado</span></div><dl>{rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd><strong>{num(value)}</strong><span>{rate(value)}</span></dd></div>)}</dl></div><p className="numbers-note">Percentuais da composição calculados sobre os votos computados deste cargo. Anulados e anulados sub judice aparecem separadamente dos nulos.{office==='5'?' Para senador, cada eleitor pode registrar dois votos; votos e eleitores têm totais diferentes.':''}</p><details className="numbers-details"><summary>Detalhamento para análise</summary><dl>{[...(['6','7','8'].includes(office)?[['Votos válidos nominais',data?.nominal],['Votos válidos de legenda',data?.legend]]:[]),['Seções pendentes de totalização',data?.sectionsPending],['Seções não instaladas',data?.sectionsUninstalled],['Seções não apuradas',data?.sectionsUncounted]].map(([label,value])=><div key={String(label)}><dt>{String(label)}</dt><dd>{num(value as number|null|undefined)}</dd></div>)}</dl><p>Dados do TSE para a localidade, o cargo e o turno selecionados. Durante a apuração, os totais são parciais. “—” indica informação indisponível ou percentual sem base de cálculo.</p><a href="https://www.tse.jus.br/eleicoes/informacoes-tecnicas-sobre-a-divulgacao-de-resultados" target="_blank" rel="noreferrer">Documentação dos dados do TSE</a></details></section>;
}
